.TH unopkg "1" "2026-04-09" "可圈office Extension Manager" "User Command"
.SH "Name"
unopkg \- 可圈office extension manager
.SH SYNOPSIS
.B unopkg
[\fBadd\fR] <\fIoptions\fR> \fIextension-path...\fR
.br
.B unopkg
[\fBremove\fR] <\fIoptions\fR> \fIextension-identifier...\fR
.br
.B unopkg
[\fBlist\fR] <\fIoptions\fR> \fIextension-identifier...\fR
.br
.B unopkg
[\fBreinstall\fR] <\fIoptions\fR>
.br
.B unopkg
[\fBgui\fR]
.br
.B unopkg
[\fB--help\fR|\fB-h\fR]

.SH DESCRIPTION
可圈office supports deployable extensions for document workflows, templates,
language tools, import/export filters, and integration components.

This tool manages extensions from the command line for the current user or for
the shared installation.

.SH SUB\-COMMANDS
.TP
\fBadd\fR
add the given extensions
.TP
\fBremove\fR
remove extensions by the given identifiers
.TP
\fBreinstall\fR
reinstall all deployed extensions (only for experts)
.TP
\fBlist\fR
list information about the deployed extensions
.TP
\fBgui\fR
raise Extensions dialog

.SH OPTIONS
.TP
\fB\-\-help\fR|\fB\-h\fR
display help and exit
.TP
\fB\-\-version\fR|\fB\-V\fR
output version information and exit
.TP
\fB--verbose\fR|\fB\-v\fR
verbose output
.TP
\fB\-\-force\fR|\fB\-f\fR
force overwriting existing extensions
.TP
\fB\-\-log\-file\fR <\fIfile\fR>
custom log file; the default one is <cache-dir>/log.txt
.TP
\fB\-\-shared\fR|\fB\-f\fR
operate on the system installation deployment context; use only when no
concurrent Office process(es) are running! (only for experts)
.TP
\fB\-\-deployment\-context\fR <\fIcontext\fR>
operate on explicit deployment context (only for experts)


.SH TROUBLESHOOTING PROBLEMS
If an extension cannot be added or removed, make sure no other Office process
is running and verify that the target deployment context is writable.
.SH SEE ALSO
.BR libreoffice (1)
.SH AUTHOR
This manual page was created by Petr Mladek <pmladek@suse.cz>.
