# -*- Mode: makefile-gmake; tab-width: 4; indent-tabs-mode: t -*-
#
# CN HF templates: zh-CN/kq/hf/<ascii-id>.ot* — UI titles from catalog.json
# Regenerated by bin/kqoffice-stage-hf-package.sh
#

$(eval $(call gb_Package_Package,extras_kq_cn_hf,$(SRCDIR)/extras/source/templates))

$(eval $(call gb_Package_add_files_with_dir,extras_kq_cn_hf,$(LIBO_SHARE_FOLDER)/template/common,\
	zh-CN/kq/catalog.json \
	zh-CN/kq/hf/hf_a01_monthly.ott \
	zh-CN/kq/hf/hf_a02_project_plan.ott \
	zh-CN/kq/hf/hf_a03_purchase_cmp.ots \
	zh-CN/kq/hf/hf_a04_attendance.ots \
	zh-CN/kq/hf/hf_a05_budget.ots \
	zh-CN/kq/hf/hf_a06_customer.ots \
	zh-CN/kq/hf/hf_a07_inventory.ots \
	zh-CN/kq/hf/hf_a08_marketing.otp \
	zh-CN/kq/hf/hf_a08_pitch.otp \
	zh-CN/kq/hf/hf_a09_launch.otp \
	zh-CN/kq/hf/hf_a09_training.otp \
	zh-CN/kq/hf/hf_a10_review.otp \
	zh-CN/kq/hf/hf_a11_labor.ott \
	zh-CN/kq/hf/hf_a12_nda.ott \
	zh-CN/kq/hf/hf_a13_purchase.ott \
	zh-CN/kq/hf/hf_a15_letter.ott \
	zh-CN/kq/hf/hf_a16_resume.ott \
	zh-CN/kq/hf/hf_a17_kpi.ots \
	zh-CN/kq/hf/hf_a18_collection.ots \
	zh-CN/kq/hf/hf_a19_recruit.ots \
	zh-CN/kq/hf/hf_a_data_review.otp \
	zh-CN/kq/hf/hf_a_ops_month.otp \
	zh-CN/kq/hf/hf_s01_daily.ott \
	zh-CN/kq/hf/hf_s01_weekly.ott \
	zh-CN/kq/hf/hf_s02_minutes.ott \
	zh-CN/kq/hf/hf_s03_todo.ots \
	zh-CN/kq/hf/hf_s04_expense.ots \
	zh-CN/kq/hf/hf_s05_leave.ott \
	zh-CN/kq/hf/hf_s06_sales.ots \
	zh-CN/kq/hf/hf_s07_schedule.ots \
	zh-CN/kq/hf/hf_s08_weekly_deck.otp \
	zh-CN/kq/hf/hf_s09_notice.ott \
	zh-CN/kq/hf/hf_s10_quote.ott \
))

# vim: set noet sw=4 ts=4:
